image:
  file: .gitpod.Dockerfile

tasks:
  - name: deps
    init: yarn && gp sync-done deps

  - name: Start
    init: gp sync-await deps && node env.js
    command: |
      yarn dev

ports:
  - port: 3000
    visibility: public
    onOpen: ignore
  - port: 6363
    visibility: public
    onOpen: ignore
